### ISSUE TITLE
Physutil doesn't run in Jupyter notebook

### ISSUE THREAD

**Issue by zimmermant** [perlatmsu/physutil#12]
I suspect this is nothing more than replacing 'visual' with 'vpython' in a number of places

**Comment by dannycab** [comment]
What error does it produce? Sorry, I'm not near a computer with Jupyter right now.

**Comment by zimmermant** [comment]
```ImportError: No module named visual```

This is because it's called vpython not visual in Jupyter

**Comment by dannycab** [comment]
I think I've fixed this by creating another module (physutil_jupyter), which no longer calls visual. I'm going through the order issues now.

**Comment by dannycab** [comment]
The new module physutil_jupyter.py fixes this.
