### ISSUE TITLE
PhysAxis results in "AttributeError: 'int' object has no attribute 'x'"

### ISSUE THREAD

**Issue by zimmermant** [perlatmsu/physutil#13]
Tried example code and got this error
```
from vpython import *
from physutil import *
 
track = box(pos=vector(0,-0.05,0), size=(5.0,0.05,0.10), color=color.white)
axis = PhysAxis(track, 10)
```

**Comment by dannycab** [comment]
I got this error with the updated version for jupyter:

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-4954012824d4> in <module>()
      1 track = box(pos=vector(0,-0.05,0), size=vector(5.0,0.05,0.10), color=color.white)
----> 2 axis = PhysAxis(track, 10)

/Users/danny/Desktop/physutil_jupyter.py in __init__(self, obj, numLabels, axisType, axis, startPos, length, labels, labelOrientation, axisColor, labelColor)
    292                 self.labelShift =  vector(0.1*self.length,0,0)
    293 
--> 294             self.__reorient()
    295         except TypeError as err:
    296             print("**********TYPE ERROR**********")

/Users/danny/Desktop/physutil_jupyter.py in __reorient(self)
    372             else:
    373                 self.intervalMarkers.append(
--> 374                     points(pos=intervalPos,color=self.axisColor,size = 6) )
    375                 self.intervalLabels.append(
    376                     label(pos=intervalPos+self.labelShift, text=str(labelText),box=False,height = 8, color=self.labelColor) )

//anaconda/lib/python2.7/site-packages/vpython/vpython.pyc in __init__(self, *args1, **args)
   1807             del args['pos']
   1808 
-> 1809         super(curveMethods, self).setup(args)
   1810 
   1811         if tpos != None:

//anaconda/lib/python2.7/site-packages/vpython/vpython.pyc in setup(self, args)
    651     # set values of user-defined attributes
    652         for key, value in args.items(): # Assign all other properties
--> 653             setattr(self, key, value)
    654 
    655         cmd = {"cmd": objName, "idx": self.idx, "attrs":[]}

//anaconda/lib/python2.7/site-packages/vpython/vpython.pyc in size(self, other)
    725     @size.setter
    726     def size(self,other):
--> 727         self._axis.value = self._axis.norm() * other.x
    728         self._size.value = other
    729         if not self._constructing:

AttributeError: 'int' object has no attribute 'x'`

That seems to be a VPython problem not a PhysUtil problem.
