### ISSUE TITLE
Error when using "breadcrumbs" in motionmap: AttributeError: 'points' object has no attribute '_size'

### ISSUE THREAD

**Issue by zimmermant** [perlatmsu/physutil#14]
Code:
```
from __future__ import division
from vpython import *
from physutil import *
 
#Create the object to be in motion and set its velocity
cart = box(pos=vector(-1.0,0,0), size=vector(0.1,0.04,0.06), color=color.green)
 
vcart = vector(0.5,0,0)
 
#Set up timing data
deltat = 0.01
t = 0
tf = 4
 
#Set up motion map
motionMap = MotionMap(cart, tf, 5, markerType="breadcrumbs", markerScale=0.5,markerColor=color.blue, labelMarkerOrder=True, dropTime=True, timeOffset=vector(0,1,0))


while t<tf:
    cart.pos+=vcart*deltat
    t+=deltat
    motionMap.update(t, vcart)`
```

Error Message:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-ed85adde1efe> in <module>()
     21     cart.pos+=vcart*deltat
     22     t+=deltat
---> 23     motionMap.update(t, vcart)

/projects/a34619e5-067a-491f-9bf6-18ace479ffb3/PHYS-281/Fall 2016/Misc/Projects/physutil.pyc in update(self, t, quantity)
    154                 elif self.markerType == "breadcrumbs":
    155                     points(pos=self.obj.pos, 
--> 156                         size=10*self.markerScale*quantity, color=self.markerColor)
    157 
    158                 #Also display timestamp if requested

/projects/a34619e5-067a-491f-9bf6-18ace479ffb3/.local/lib/python2.7/site-packages/vpython/vpython.pyc in __init__(self, *args1, **args)
   1807             del args['pos']
   1808 
-> 1809         super(curveMethods, self).setup(args)
   1810 
   1811         if tpos != None:

/projects/a34619e5-067a-491f-9bf6-18ace479ffb3/.local/lib/python2.7/site-packages/vpython/vpython.pyc in setup(self, args)
    651     # set values of user-defined attributes
    652         for key, value in args.items(): # Assign all other properties
--> 653             setattr(self, key, value)
    654 
    655         cmd = {"cmd": objName, "idx": self.idx, "attrs":[]}

/projects/a34619e5-067a-491f-9bf6-18ace479ffb3/.local/lib/python2.7/site-packages/vpython/vpython.pyc in size(self, other)
    726     def size(self,other):
    727         self._axis.value = self._axis.norm() * other.x
--> 728         self._size.value = other
    729         if not self._constructing:
    730             self.addattr('axis')

AttributeError: 'points' object has no attribute '_size'

**Comment by mnky9800n** [comment]
please edit your post to format it as code. for example, your code is missing semantic white space.

**Comment by dannycab** [comment]
This was fixed by removing the MarkerScale parameter, which used to set the size of points. Apparently, you can't set that with jupyter-vpython. I wonder if that's also a problem with Classic VPython, which I don't have installed. This issue is now resolved.
